apiVersion: gitups/v1alpha1
kind: PackageDescriptor
metadata:
  name: raw
spec:
  renderer: raw
  inputs:
    - name: message
      type: string
      default: "Hello, gitups!"
    - name: namespace
      type: string
      default: example
