apiVersion: gitups/v1alpha1
kind: PackageDescriptor
metadata:
  name: repo-secret
spec:
  renderer: raw
  inputs:
    - name: namespace
      type: string
      default: declarest-system
    - name: repoURL
      type: string
      required: true
    - name: repoUsername
      type: string
      required: true
    - name: repoPassword
      type: string
      required: true
      sensitive: true
  dependsOn:
    - declarest/install
  readiness:
    - kind: Deployment
      namespace: '{{ .Values.namespace }}'
      name: declarest
      condition: Available
