apiVersion: gitups/v1alpha1
kind: PackageDefinition
metadata:
  name: gitea
  version: 0.0.1
spec:
  role: workload
  category: source-control
  defaultInstall: helm
  defaultResources:
    - template: config
      name: default
  provides:
    - capability: git-provider
      resourceTemplate: user
      exports:
        - name: url
          from: input:rootURL
        - name: username
          from: binding:username
        - name: token
          from: placeholder
          secret: true
