apiVersion: gitups/v1alpha1
kind: PackageDefinition
metadata:
  name: keycloak
  version: 0.0.1
spec:
  role: workload
  category: identity
  defaultInstall: olm
  defaultResources:
    - template: config
      name: default
