apiVersion: gitups/v1alpha1
kind: PackageDescriptor
metadata:
  name: raw
spec:
  renderer: raw
  inputs:
    - name: namespace
      type: string
      default: declarest-system
    - name: image.repository
      type: string
      default: ghcr.io/crmarques/declarest
    - name: image.tag
      type: string
      default: v0.3.8
    - name: replicas
      type: int
      default: 1
