apiVersion: gitups/v1alpha1
kind: PackageDescriptor
metadata:
  name: olm
spec:
  renderer: olm
  inputs:
    - name: namespace
      type: string
      default: argocd
    - name: olm.startingCSV
      type: string
      default: argocd-operator.v0.17.0
  dependsOn:
    - olm/install
  olm:
    package: argocd-operator
    channel: alpha
    source: operatorhubio-catalog
    sourceNamespace: olm
    startingCSV: argocd-operator.v0.17.0
    installPlanApproval: Automatic
    operatorGroupScope: AllNamespaces
