apiVersion: gitups/v1alpha1
kind: PackageDescriptor
metadata:
  name: instance
spec:
  renderer: raw
  inputs:
    - name: namespace
      type: string
      default: argocd
    - name: instance
      type: string
      default: argocd
  dependsOn:
    - argocd/install
