apiVersion: gitups/v1alpha1
kind: PackageDefinition
metadata:
  name: declarest
  version: 0.0.1
spec:
  role: controller
  category: gitops-controller
  defaultInstall: raw
  defaultResources:
    - template: config
      name: default
